import type { Product, Category } from '@aisuce/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Vegetables', slug: 'vegetables', iconUrl: '' },
  { id: '2', name: 'Fruits', slug: 'fruits', iconUrl: '' },
  { id: '3', name: 'Grains', slug: 'grains', iconUrl: '' },
  { id: '4', name: 'Tubers', slug: 'tubers', iconUrl: '' },
  { id: '5', name: 'Spices', slug: 'spices', iconUrl: '' },
  { id: '6', name: 'Legumes', slug: 'legumes', iconUrl: '' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Fresh Organic Tomatoes',
    description: 'Locally grown organic tomatoes, harvested fresh from the farm. Perfect for salads, cooking, or juicing.',
    storeId: 's1',
    categoryId: '1',
    price: 450,
    kilogram: 1,
    stock: 50,
    condition: 'Fresh' as any,
    isActive: true,
    images: [{ id: 'img1', productId: 'p1', s3Key: '', url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    title: 'Yellow Maize',
    description: 'High-quality yellow maize, suitable for food, animal feed, or processing.',
    storeId: 's2',
    categoryId: '3',
    price: 280,
    kilogram: 1,
    stock: 200,
    condition: 'Dried' as any,
    isActive: true,
    images: [{ id: 'img2', productId: 'p2', s3Key: '', url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    title: 'Fresh Cassava Tubers',
    description: 'Freshly harvested cassava tubers, rich in carbohydrates. Ready for processing or cooking.',
    storeId: 's1',
    categoryId: '4',
    price: 180,
    kilogram: 1,
    stock: 100,
    condition: 'Fresh' as any,
    isActive: true,
    images: [{ id: 'img3', productId: 'p3', s3Key: '', url: 'https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    title: 'Dry Groundnut',
    description: 'Clean, dry groundnuts. Great for oil extraction, roasting, or direct consumption.',
    storeId: 's2',
    categoryId: '6',
    price: 650,
    kilogram: 1,
    stock: 80,
    condition: 'Dried' as any,
    isActive: true,
    images: [{ id: 'img4', productId: 'p4', s3Key: '', url: 'https://images.unsplash.com/photo-1596395819057-3a8b8c7a3f5e?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    title: 'Organic Spinach Bundle',
    description: 'Fresh organic spinach leaves, hand-picked for maximum freshness and nutrition.',
    storeId: 's3',
    categoryId: '1',
    price: 220,
    kilogram: 1,
    stock: 40,
    condition: 'Fresh' as any,
    isActive: true,
    images: [{ id: 'img5', productId: 'p5', s3Key: '', url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    title: 'Premium Palm Oil',
    description: 'Freshly processed palm oil, extracted from sustainable farms. Used for cooking and food preparation.',
    storeId: 's3',
    categoryId: '1',
    price: 550,
    kilogram: 1,
    stock: 60,
    condition: 'Processed' as any,
    isActive: true,
    images: [{ id: 'img6', productId: 'p6', s3Key: '', url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=400&fit=crop', isPrimary: true }],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];